from fastapi import APIRouter, Query
from typing import Dict, Any, Optional
from ai.forecasting import DemandForecastingEngine
from backend.database.repository import repo

router = APIRouter(prefix="/forecasts", tags=["Forecasts"])
forecasting_engine = DemandForecastingEngine()


@router.get("")
def get_forecasts(
    retailer_id: Optional[str] = Query(None, description="Filter by retailer ID"),
    product_id: Optional[str] = Query(None, description="Filter by product ID")
) -> Dict[str, Any]:
    """
    Retrieves stored demand forecasts generated by the ML engine.
    """
    forecasts = repo.get_all("forecasts")

    if retailer_id:
        forecasts = [f for f in forecasts if f.get("retailer_id") == retailer_id]
    if product_id:
        forecasts = [f for f in forecasts if f.get("product_id") == product_id]

    return {
        "status": "success",
        "count": len(forecasts),
        "data": forecasts
    }


@router.post("/generate-forecasts")
def trigger_generate_forecasts(horizon_days: int = 30) -> Dict[str, Any]:
    """
    Triggers the AI Demand Forecasting Pipeline (Moving Average + Random Forest Regressor)
    across all retailers and catalog products.
    """
    generated = forecasting_engine.run_all_forecasts(horizon_days=horizon_days)

    return {
        "status": "success",
        "message": f"Successfully generated and stored {len(generated)} demand forecasts.",
        "count": len(generated),
        "horizon_days": horizon_days,
        "sample": generated[:3] if generated else []
    }
