/**
 * Realistic initial procurement orders for Samooh Wholesale Suppliers.
 * Matches backend seed_data.py and domain models in models/supplier.py.
 */

export const INITIAL_SUPPLIER_ORDERS = [
  {
    id: "sord_1041",
    order_no: "SAM-PO-1041",
    supplier_id: "sup_01",
    pool_id: "pool_1041",
    product_id: "prod_001",
    product_name: "Sona Masoori Raw Rice (25kg Bag)",
    category: "Grains & Staples",
    retailer_count: 6,
    pooled_quantity: 36.0,
    unit: "bag",
    unit_weight_kg: 25.0,
    total_weight_kg: 900.0,
    supplier_moq: 20.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 1250.0,
    quantity_tier_price: 1180.0,
    discount_pct: 2.0,
    additional_discount: 23.60,
    final_unit_price: 1156.40,
    gross_order_value: 42480.0,
    discount_amount: 849.60,
    final_order_value: 41630.40,
    moq_at_acceptance: null,
    price_at_acceptance: null,
    accepted_at: null,
    delivery_cluster: "Secunderabad Cluster Hub #3",
    delivery_distance_km: 4.5,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "Small Commercial Vehicle (SCV) / Tata Ace",
      vehicle_capacity_kg: 1000.0,
      total_load_kg: 900.0,
      capacity_utilization_pct: 90.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 820.0,
      cost_per_retailer_inr: 136.67,
      transit_time_minutes: 25
    },
    status: "PENDING",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 3600000).toISOString(), description: "Group order formed by 6 Kirana retailers; awaiting supplier review", actor: "SYSTEM" }
    ],
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString()
  },
  {
    id: "sord_1042",
    order_no: "SAM-PO-1042",
    supplier_id: "sup_01",
    pool_id: "pool_1042",
    product_id: "prod_003",
    product_name: "Aashirvaad Sharbati Whole Wheat Atta (10kg)",
    category: "Flours & Grains",
    retailer_count: 8,
    pooled_quantity: 60.0,
    unit: "bag",
    unit_weight_kg: 10.0,
    total_weight_kg: 600.0,
    supplier_moq: 30.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 420.0,
    quantity_tier_price: 395.0,
    discount_pct: 3.0,
    additional_discount: 11.85,
    final_unit_price: 383.15,
    gross_order_value: 23700.0,
    discount_amount: 711.00,
    final_order_value: 22989.00,
    moq_at_acceptance: null,
    price_at_acceptance: null,
    accepted_at: null,
    delivery_cluster: "Hyderabad West - Kukatpally Cluster",
    delivery_distance_km: 6.8,
    estimated_delivery_time_days: 2,
    transport_info: {
      recommended_vehicle: "Small Commercial Vehicle (SCV) / Tata Ace",
      vehicle_capacity_kg: 1000.0,
      total_load_kg: 600.0,
      capacity_utilization_pct: 60.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 780.0,
      cost_per_retailer_inr: 97.50,
      transit_time_minutes: 28
    },
    status: "PENDING",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 7200000).toISOString(), description: "8 Kirana stores pooled 60 bags demand; ready for review", actor: "SYSTEM" }
    ],
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString()
  },
  {
    id: "sord_1043",
    order_no: "SAM-PO-1043",
    supplier_id: "sup_01",
    pool_id: "pool_1043",
    product_id: "prod_004",
    product_name: "Madhur Pure & Hygienic Refined Sugar S-30 (50kg)",
    category: "Sugar & Jaggery",
    retailer_count: 7,
    pooled_quantity: 24.0,
    unit: "bag",
    unit_weight_kg: 50.0,
    total_weight_kg: 1200.0,
    supplier_moq: 15.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 2150.0,
    quantity_tier_price: 2080.0,
    discount_pct: 2.0,
    additional_discount: 41.60,
    final_unit_price: 2038.40,
    gross_order_value: 49920.0,
    discount_amount: 998.40,
    final_order_value: 48921.60,
    moq_at_acceptance: 15.0,
    price_at_acceptance: 2038.40,
    accepted_at: new Date(Date.now() - 21600000).toISOString(),
    delivery_cluster: "Charminar South Cluster Hub",
    delivery_distance_km: 5.2,
    estimated_delivery_time_days: 2,
    transport_info: {
      recommended_vehicle: "Medium Commercial Vehicle (MCV) / Tata 407",
      vehicle_capacity_kg: 2500.0,
      total_load_kg: 1200.0,
      capacity_utilization_pct: 48.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 1450.0,
      cost_per_retailer_inr: 207.14,
      transit_time_minutes: 24
    },
    status: "ACCEPTED",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 36000000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 21600000).toISOString(), description: "Order accepted; inventory reserved and price locked", actor: "SUPPLIER (sup_01)" }
    ],
    created_at: new Date(Date.now() - 36000000).toISOString(),
    updated_at: new Date(Date.now() - 21600000).toISOString()
  },
  {
    id: "sord_1044",
    order_no: "SAM-PO-1044",
    supplier_id: "sup_01",
    pool_id: "pool_1044",
    product_id: "prod_002",
    product_name: "Tata Sampann Unpolished Desi Toor Dal (1kg)",
    category: "Pulses & Dals",
    retailer_count: 5,
    pooled_quantity: 280.0,
    unit: "kg",
    unit_weight_kg: 1.0,
    total_weight_kg: 280.0,
    supplier_moq: 100.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 155.0,
    quantity_tier_price: 146.0,
    discount_pct: 2.5,
    additional_discount: 3.65,
    final_unit_price: 142.35,
    gross_order_value: 40880.0,
    discount_amount: 1022.00,
    final_order_value: 39858.00,
    moq_at_acceptance: 100.0,
    price_at_acceptance: 142.35,
    accepted_at: new Date(Date.now() - 28800000).toISOString(),
    delivery_cluster: "Madhapur Tech Zone Cluster",
    delivery_distance_km: 7.4,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "3-Wheeler E-Loader / Piaggio Ape E-City",
      vehicle_capacity_kg: 500.0,
      total_load_kg: 280.0,
      capacity_utilization_pct: 56.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 420.0,
      cost_per_retailer_inr: 84.00,
      transit_time_minutes: 22
    },
    status: "ACCEPTED",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 43200000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 28800000).toISOString(), description: "Order confirmed for dispatch scheduling", actor: "SUPPLIER (sup_01)" }
    ],
    created_at: new Date(Date.now() - 43200000).toISOString(),
    updated_at: new Date(Date.now() - 28800000).toISOString()
  },
  {
    id: "sord_1045",
    order_no: "SAM-PO-1045",
    supplier_id: "sup_01",
    pool_id: "pool_1045",
    product_id: "prod_005",
    product_name: "Fortune Sunlite Refined Sunflower Oil (15L Tin)",
    category: "Edible Oils",
    retailer_count: 6,
    pooled_quantity: 32.0,
    unit: "tin",
    unit_weight_kg: 14.2,
    total_weight_kg: 454.4,
    supplier_moq: 20.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 1680.0,
    quantity_tier_price: 1610.0,
    discount_pct: 2.0,
    additional_discount: 32.20,
    final_unit_price: 1577.80,
    gross_order_value: 51520.0,
    discount_amount: 1030.40,
    final_order_value: 50489.60,
    moq_at_acceptance: 20.0,
    price_at_acceptance: 1577.80,
    accepted_at: new Date(Date.now() - 86400000).toISOString(),
    delivery_cluster: "Dilsukhnagar Commercial Hub",
    delivery_distance_km: 4.9,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "Small Commercial Vehicle (SCV) / Tata Ace",
      vehicle_capacity_kg: 1000.0,
      total_load_kg: 454.4,
      capacity_utilization_pct: 45.4,
      vehicles_required: 1,
      estimated_transport_cost_inr: 750.0,
      cost_per_retailer_inr: 125.00,
      transit_time_minutes: 20
    },
    status: "PROCESSING",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 100800000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 86400000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "PROCESSING", timestamp: new Date(Date.now() - 50400000).toISOString(), description: "Warehouse packaging and palletizing tins", actor: "SUPPLIER (sup_01)" }
    ],
    created_at: new Date(Date.now() - 100800000).toISOString(),
    updated_at: new Date(Date.now() - 50400000).toISOString()
  },
  {
    id: "sord_1046",
    order_no: "SAM-PO-1046",
    supplier_id: "sup_01",
    pool_id: "pool_1046",
    product_id: "prod_008",
    product_name: "Parle-G Gold Glucose Biscuits (Pack of 50)",
    category: "Packaged Snacks",
    retailer_count: 9,
    pooled_quantity: 48.0,
    unit: "pack",
    unit_weight_kg: 4.0,
    total_weight_kg: 192.0,
    supplier_moq: 25.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 450.0,
    quantity_tier_price: 425.0,
    discount_pct: 4.0,
    additional_discount: 17.00,
    final_unit_price: 408.00,
    gross_order_value: 20400.0,
    discount_amount: 816.00,
    final_order_value: 19584.00,
    moq_at_acceptance: 25.0,
    price_at_acceptance: 408.00,
    accepted_at: new Date(Date.now() - 115200000).toISOString(),
    delivery_cluster: "Begumpet Central Cluster",
    delivery_distance_km: 3.2,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "3-Wheeler E-Loader / Piaggio Ape E-City",
      vehicle_capacity_kg: 500.0,
      total_load_kg: 192.0,
      capacity_utilization_pct: 38.4,
      vehicles_required: 1,
      estimated_transport_cost_inr: 380.0,
      cost_per_retailer_inr: 42.22,
      transit_time_minutes: 15
    },
    status: "PROCESSING",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 172800000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 115200000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "PROCESSING", timestamp: new Date(Date.now() - 36000000).toISOString(), description: "Cartons labeled with Kirana QR codes", actor: "SUPPLIER (sup_01)" }
    ],
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 36000000).toISOString()
  },
  {
    id: "sord_1047",
    order_no: "SAM-PO-1047",
    supplier_id: "sup_01",
    pool_id: "pool_1047",
    product_id: "prod_007",
    product_name: "Brooke Bond Red Label Strong CTC Tea (1kg)",
    category: "Beverages",
    retailer_count: 8,
    pooled_quantity: 120.0,
    unit: "kg",
    unit_weight_kg: 1.0,
    total_weight_kg: 120.0,
    supplier_moq: 50.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 480.0,
    quantity_tier_price: 450.0,
    discount_pct: 3.0,
    additional_discount: 13.50,
    final_unit_price: 436.50,
    gross_order_value: 54000.0,
    discount_amount: 1620.00,
    final_order_value: 52380.00,
    moq_at_acceptance: 50.0,
    price_at_acceptance: 436.50,
    accepted_at: new Date(Date.now() - 129600000).toISOString(),
    delivery_cluster: "Malkajgiri North Cluster",
    delivery_distance_km: 5.8,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "3-Wheeler E-Loader / Piaggio Ape E-City",
      vehicle_capacity_kg: 500.0,
      total_load_kg: 120.0,
      capacity_utilization_pct: 24.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 395.0,
      cost_per_retailer_inr: 49.38,
      transit_time_minutes: 22
    },
    status: "PROCESSING",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 172800000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 129600000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "PROCESSING", timestamp: new Date(Date.now() - 28800000).toISOString(), description: "Sorting by retailer batches", actor: "SUPPLIER (sup_01)" }
    ],
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 28800000).toISOString()
  },
  {
    id: "sord_1048",
    order_no: "SAM-PO-1048",
    supplier_id: "sup_01",
    pool_id: "pool_1048",
    product_id: "prod_009",
    product_name: "Tata Salt Vacuum Evaporated Iodized (1kg)",
    category: "Salt & Condiments",
    retailer_count: 11,
    pooled_quantity: 500.0,
    unit: "kg",
    unit_weight_kg: 1.0,
    total_weight_kg: 500.0,
    supplier_moq: 200.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 24.0,
    quantity_tier_price: 21.50,
    discount_pct: 2.0,
    additional_discount: 0.43,
    final_unit_price: 21.07,
    gross_order_value: 10750.0,
    discount_amount: 215.00,
    final_order_value: 10535.00,
    moq_at_acceptance: 200.0,
    price_at_acceptance: 21.07,
    accepted_at: new Date(Date.now() - 172800000).toISOString(),
    delivery_cluster: "Kukatpally Retail Hub #2",
    delivery_distance_km: 6.1,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "Small Commercial Vehicle (SCV) / Tata Ace",
      vehicle_capacity_kg: 1000.0,
      total_load_kg: 500.0,
      capacity_utilization_pct: 50.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 760.0,
      cost_per_retailer_inr: 69.09,
      transit_time_minutes: 25
    },
    status: "READY_FOR_DISPATCH",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 259200000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 172800000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "PROCESSING", timestamp: new Date(Date.now() - 86400000).toISOString(), description: "Packed in bulk sacks", actor: "SUPPLIER (sup_01)" },
      { status: "READY_FOR_DISPATCH", timestamp: new Date(Date.now() - 14400000).toISOString(), description: "Staged at dispatch dock #2 for pickup", actor: "SUPPLIER (sup_01)" }
    ],
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date(Date.now() - 14400000).toISOString()
  },
  {
    id: "sord_1049",
    order_no: "SAM-PO-1049",
    supplier_id: "sup_01",
    pool_id: "pool_1049",
    product_id: "prod_010",
    product_name: "Amulya Dairy Whitener Milk Powder (1kg Pouch)",
    category: "Dairy & Staples",
    retailer_count: 4,
    pooled_quantity: 90.0,
    unit: "kg",
    unit_weight_kg: 1.0,
    total_weight_kg: 90.0,
    supplier_moq: 40.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 385.0,
    quantity_tier_price: 365.0,
    discount_pct: 2.0,
    additional_discount: 7.30,
    final_unit_price: 357.70,
    gross_order_value: 32850.0,
    discount_amount: 657.00,
    final_order_value: 32193.00,
    moq_at_acceptance: 40.0,
    price_at_acceptance: 357.70,
    accepted_at: new Date(Date.now() - 172800000).toISOString(),
    delivery_cluster: "Secunderabad Station Cluster",
    delivery_distance_km: 3.8,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "3-Wheeler E-Loader / Piaggio Ape E-City",
      vehicle_capacity_kg: 500.0,
      total_load_kg: 90.0,
      capacity_utilization_pct: 18.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 360.0,
      cost_per_retailer_inr: 90.00,
      transit_time_minutes: 18
    },
    status: "READY_FOR_DISPATCH",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 259200000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 172800000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "READY_FOR_DISPATCH", timestamp: new Date(Date.now() - 10800000).toISOString(), description: "Quality inspected & ready for logistics partner pickup", actor: "SUPPLIER (sup_01)" }
    ],
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date(Date.now() - 10800000).toISOString()
  },
  {
    id: "sord_1050",
    order_no: "SAM-PO-1050",
    supplier_id: "sup_01",
    pool_id: "pool_1050",
    product_id: "prod_011",
    product_name: "Everest Pure Turmeric Powder (500g Pouch)",
    category: "Spices & Masalas",
    retailer_count: 7,
    pooled_quantity: 150.0,
    unit: "pack",
    unit_weight_kg: 0.5,
    total_weight_kg: 75.0,
    supplier_moq: 60.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 115.0,
    quantity_tier_price: 108.0,
    discount_pct: 3.0,
    additional_discount: 3.24,
    final_unit_price: 104.76,
    gross_order_value: 16200.0,
    discount_amount: 486.00,
    final_order_value: 15714.00,
    moq_at_acceptance: 60.0,
    price_at_acceptance: 104.76,
    accepted_at: new Date(Date.now() - 259200000).toISOString(),
    delivery_cluster: "Banjara Hills Cluster",
    delivery_distance_km: 4.1,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "3-Wheeler E-Loader / Piaggio Ape E-City",
      vehicle_capacity_kg: 500.0,
      total_load_kg: 75.0,
      capacity_utilization_pct: 15.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 375.0,
      cost_per_retailer_inr: 53.57,
      transit_time_minutes: 18
    },
    status: "DISPATCHED",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 345600000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 259200000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "READY_FOR_DISPATCH", timestamp: new Date(Date.now() - 172800000).toISOString(), description: "Handed over to carrier", actor: "SUPPLIER (sup_01)" },
      { status: "DISPATCHED", timestamp: new Date(Date.now() - 18000000).toISOString(), description: "Vehicle en route (Driver: Ramesh Kumar, TS 09 EA 4192)", actor: "LOGISTICS_DRIVER" }
    ],
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: new Date(Date.now() - 18000000).toISOString()
  },
  {
    id: "sord_1051",
    order_no: "SAM-PO-1051",
    supplier_id: "sup_01",
    pool_id: "pool_1051",
    product_id: "prod_012",
    product_name: "Gemini Pure Kachi Ghani Mustard Oil (1L Bottle)",
    category: "Edible Oils",
    retailer_count: 6,
    pooled_quantity: 210.0,
    unit: "bottle",
    unit_weight_kg: 0.92,
    total_weight_kg: 193.2,
    supplier_moq: 80.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 142.0,
    quantity_tier_price: 134.0,
    discount_pct: 2.0,
    additional_discount: 2.68,
    final_unit_price: 131.32,
    gross_order_value: 28140.0,
    discount_amount: 562.80,
    final_order_value: 27577.20,
    moq_at_acceptance: 80.0,
    price_at_acceptance: 131.32,
    accepted_at: new Date(Date.now() - 259200000).toISOString(),
    delivery_cluster: "Jubilee Hills Cluster",
    delivery_distance_km: 5.0,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "3-Wheeler E-Loader / Piaggio Ape E-City",
      vehicle_capacity_kg: 500.0,
      total_load_kg: 193.2,
      capacity_utilization_pct: 38.6,
      vehicles_required: 1,
      estimated_transport_cost_inr: 410.0,
      cost_per_retailer_inr: 68.33,
      transit_time_minutes: 20
    },
    status: "DISPATCHED",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 345600000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 259200000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "DISPATCHED", timestamp: new Date(Date.now() - 7200000).toISOString(), description: "Loaded on multi-stop delivery route", actor: "LOGISTICS_DRIVER" }
    ],
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString()
  },
  {
    id: "sord_1052",
    order_no: "SAM-PO-1052",
    supplier_id: "sup_01",
    pool_id: "pool_1052",
    product_id: "prod_014",
    product_name: "India Gate Feast Rozzana Basmati Rice (10kg)",
    category: "Grains & Staples",
    retailer_count: 8,
    pooled_quantity: 80.0,
    unit: "bag",
    unit_weight_kg: 10.0,
    total_weight_kg: 800.0,
    supplier_moq: 30.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 890.0,
    quantity_tier_price: 840.0,
    discount_pct: 4.0,
    additional_discount: 33.60,
    final_unit_price: 806.40,
    gross_order_value: 67200.0,
    discount_amount: 2688.00,
    final_order_value: 64512.00,
    moq_at_acceptance: 30.0,
    price_at_acceptance: 806.40,
    accepted_at: new Date(Date.now() - 432000000).toISOString(),
    delivery_cluster: "Gachibowli Tech Cluster",
    delivery_distance_km: 8.2,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "Small Commercial Vehicle (SCV) / Tata Ace",
      vehicle_capacity_kg: 1000.0,
      total_load_kg: 800.0,
      capacity_utilization_pct: 80.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 850.0,
      cost_per_retailer_inr: 106.25,
      transit_time_minutes: 30
    },
    status: "DELIVERED",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 518400000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 432000000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "DISPATCHED", timestamp: new Date(Date.now() - 345600000).toISOString(), description: "Dispatched", actor: "SUPPLIER (sup_01)" },
      { status: "DELIVERED", timestamp: new Date(Date.now() - 259200000).toISOString(), description: "Delivered to all 8 Kirana stores with OTP verification", actor: "LOGISTICS_DRIVER" }
    ],
    created_at: new Date(Date.now() - 518400000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString()
  },
  {
    id: "sord_1053",
    order_no: "SAM-PO-1053",
    supplier_id: "sup_01",
    pool_id: "pool_1053",
    product_id: "prod_013",
    product_name: "Everest Tikhalal Red Chilli Powder (500g Pouch)",
    category: "Spices & Masalas",
    retailer_count: 5,
    pooled_quantity: 110.0,
    unit: "pack",
    unit_weight_kg: 0.5,
    total_weight_kg: 55.0,
    supplier_moq: 50.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 145.0,
    quantity_tier_price: 136.0,
    discount_pct: 2.5,
    additional_discount: 3.40,
    final_unit_price: 132.60,
    gross_order_value: 14960.0,
    discount_amount: 374.00,
    final_order_value: 14586.00,
    moq_at_acceptance: 50.0,
    price_at_acceptance: 132.60,
    accepted_at: new Date(Date.now() - 432000000).toISOString(),
    delivery_cluster: "Amberpet East Cluster",
    delivery_distance_km: 4.6,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "3-Wheeler E-Loader / Piaggio Ape E-City",
      vehicle_capacity_kg: 500.0,
      total_load_kg: 55.0,
      capacity_utilization_pct: 11.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 350.0,
      cost_per_retailer_inr: 70.00,
      transit_time_minutes: 16
    },
    status: "DELIVERED",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 518400000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 432000000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_01)" },
      { status: "DISPATCHED", timestamp: new Date(Date.now() - 345600000).toISOString(), description: "Dispatched", actor: "SUPPLIER (sup_01)" },
      { status: "DELIVERED", timestamp: new Date(Date.now() - 259200000).toISOString(), description: "All 5 deliveries received successfully", actor: "LOGISTICS_DRIVER" }
    ],
    created_at: new Date(Date.now() - 518400000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString()
  },
  {
    id: "sord_1054",
    order_no: "SAM-PO-1054",
    supplier_id: "sup_01",
    pool_id: "pool_1054",
    product_id: "prod_015",
    product_name: "Catch Table Salt Sprinkler (200g)",
    category: "Salt & Condiments",
    retailer_count: 12,
    pooled_quantity: 400.0,
    unit: "pack",
    unit_weight_kg: 0.2,
    total_weight_kg: 80.0,
    supplier_moq: 150.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 38.0,
    quantity_tier_price: 34.0,
    discount_pct: 3.0,
    additional_discount: 1.02,
    final_unit_price: 32.98,
    gross_order_value: 13600.0,
    discount_amount: 408.00,
    final_order_value: 13192.00,
    moq_at_acceptance: null,
    price_at_acceptance: null,
    accepted_at: null,
    delivery_cluster: "Nampally Station Road Cluster",
    delivery_distance_km: 3.9,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "3-Wheeler E-Loader / Piaggio Ape E-City",
      vehicle_capacity_kg: 500.0,
      total_load_kg: 80.0,
      capacity_utilization_pct: 16.0,
      vehicles_required: 1,
      estimated_transport_cost_inr: 360.0,
      cost_per_retailer_inr: 30.00,
      transit_time_minutes: 18
    },
    status: "REJECTED",
    rejection_reason: "Temporary packaging line maintenance scheduled - 24hr fulfillment SLA cannot be guaranteed.",
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 86400000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "REJECTED", timestamp: new Date(Date.now() - 64800000).toISOString(), description: "Order declined due to facility packaging maintenance window", actor: "SUPPLIER (sup_01)" }
    ],
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 64800000).toISOString()
  },
  {
    id: "sord_2001",
    order_no: "SAM-PO-2001",
    supplier_id: "sup_02",
    pool_id: "pool_2001",
    product_id: "prod_006",
    product_name: "Freedom Sunflower Oil (15L Tin)",
    category: "Edible Oils",
    retailer_count: 5,
    pooled_quantity: 42.0,
    unit: "tin",
    unit_weight_kg: 14.2,
    total_weight_kg: 596.4,
    supplier_moq: 35.0,
    moq_status: "SATISFIED",
    base_wholesale_price: 1620.0,
    quantity_tier_price: 1620.0,
    discount_pct: 3.0,
    additional_discount: 48.60,
    final_unit_price: 1571.40,
    gross_order_value: 68040.0,
    discount_amount: 2041.20,
    final_order_value: 65998.80,
    moq_at_acceptance: 35.0,
    price_at_acceptance: 1571.40,
    accepted_at: new Date(Date.now() - 432000000).toISOString(),
    delivery_cluster: "Hyderabad East Cluster #7",
    delivery_distance_km: 6.5,
    estimated_delivery_time_days: 1,
    transport_info: {
      recommended_vehicle: "Small Commercial Vehicle (SCV) / Tata Ace",
      vehicle_capacity_kg: 1000.0,
      total_load_kg: 596.4,
      capacity_utilization_pct: 59.6,
      vehicles_required: 1,
      estimated_transport_cost_inr: 793.0,
      cost_per_retailer_inr: 158.60,
      transit_time_minutes: 22
    },
    status: "DELIVERED",
    rejection_reason: null,
    timeline: [
      { status: "PENDING", timestamp: new Date(Date.now() - 518400000).toISOString(), description: "Group formed", actor: "SYSTEM" },
      { status: "ACCEPTED", timestamp: new Date(Date.now() - 432000000).toISOString(), description: "Accepted", actor: "SUPPLIER (sup_02)" },
      { status: "DISPATCHED", timestamp: new Date(Date.now() - 345600000).toISOString(), description: "Dispatched via Tata Ace (AP 28 TE 4410)", actor: "SUPPLIER (sup_02)" },
      { status: "DELIVERED", timestamp: new Date(Date.now() - 259200000).toISOString(), description: "Delivered to all 5 stores", actor: "LOGISTICS_DRIVER" }
    ],
    created_at: new Date(Date.now() - 518400000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString()
  }
];
