export const MOCK_DASHBOARD = {
  metrics: {
    total_retailers: 30,
    total_catalog_products: 20,
    total_active_pools: 12,
    pools_achieved_threshold: 9,
    total_community_savings_inr: 84520.0,
    total_forecasts_generated: 120,
    total_recommendations: 12,
    average_savings_percentage: 18.5
  },
  category_breakdown: {
    "Grains": 5,
    "Oils": 4,
    "Spices": 4,
    "Beverages": 4,
    "Personal Care": 3
  },
  monthly_savings_trend: [
    { month: 'Jan', savings: 12400, pools: 4, volume: 140 },
    { month: 'Feb', savings: 18900, pools: 6, volume: 210 },
    { month: 'Mar', savings: 24500, pools: 8, volume: 290 },
    { month: 'Apr', savings: 38200, pools: 9, volume: 380 },
    { month: 'May', savings: 59000, pools: 11, volume: 510 },
    { month: 'Jun', savings: 84520, pools: 12, volume: 640 }
  ]
};

export const MOCK_RECOMMENDATIONS = [
  {
    id: "rec_001",
    product_id: "prod_001",
    product_name: "Sona Masoori Rice (25kg Bag)",
    category: "Grains",
    pool_id: "pool_001",
    retailer_ids: ["ret_001", "ret_002", "ret_005", "ret_008"],
    retailer_names: [
      "Sri Lakshmi Kirana Store",
      "Balaji Superette",
      "Sai Ram Provisions",
      "Venkateshwara Traders"
    ],
    threshold_status: "ACHIEVED",
    threshold_quantity: 40.0,
    current_pool_quantity: 43.5,
    estimated_total_savings: 11745.0,
    estimated_savings_percentage: 18.6,
    average_cluster_distance_km: 1.85,
    unit_retail_price: 1450.0,
    unit_wholesale_price: 1180.0,
    explanation: "A cluster of 4 nearby Kirana stores (within 1.85 km radius) has a combined 30-day forecast demand of 43.5 bags. This exceeds the supplier wholesale threshold of 40.0 bags, unlocking an estimated total group savings of ₹11,745.00 (18.6% discount).",
    score: 0.96,
    pooled_inventory: {
      product_id: "prod_001",
      product_name: "Sona Masoori Rice (25kg Bag)",
      unit: "bag",
      retailer_count: 4,
      total_quantity: 43.5,
      unit_weight_kg: 25.0,
      total_weight_kg: 1087.5,
      supplier_moq: 40.0,
      moq_satisfied: true,
      moq_deficit: 0.0,
      retailer_demands: { ret_001: 12.0, ret_002: 10.5, ret_005: 11.0, ret_008: 10.0 }
    },
    transport: {
      total_load_kg: 1087.5,
      total_quantity: 43.5,
      unit: "bag",
      recommended_vehicle: "Eicher Pro 2049 / Partner (MGV)",
      vehicle_type: "MGV",
      vehicle_capacity_kg: 2500.0,
      capacity_utilization: 0.435,
      capacity_utilization_pct: 43.5,
      vehicles_required: 1,
      estimated_distance_km: 1.85,
      estimated_transit_time_mins: 42,
      delivery_stops_count: 4,
      estimated_total_cost_inr: 885.0,
      cost_per_retailer_inr: 221.25,
      individual_transport_cost_inr: 1800.0,
      transport_savings_inr: 915.0,
      transport_status: "SUITABLE",
      reason: "Eicher Pro 2049 (2,500 kg) selected: provides sufficient capacity for 1,087.5 kg pooled load across 4 stores within 1.85 km radius, saving ₹915.00 vs individual transport.",
      vehicle_availability: "Available (In Fleet)",
      alternative_options: [
        { vehicle_id: "veh_scv_tata_ace", vehicle_name: "Tata Ace (SCV)", capacity_kg: 1000, capacity_utilization_pct: 108.8, is_feasible: false, estimated_cost_inr: 720, rejection_reason: "Payload exceeds capacity (1,000 kg < 1,087.5 kg)" },
        { vehicle_id: "veh_mgv_eicher_pro", vehicle_name: "Eicher Pro (MGV)", capacity_kg: 2500, capacity_utilization_pct: 43.5, is_feasible: true, estimated_cost_inr: 885 }
      ]
    },
    supplier_evaluation: {
      is_feasible: true,
      selected_supplier_id: "sup_01",
      selected_supplier_name: "Hyderabad Agro Wholesale Hub",
      moq: 40.0,
      available_stock: 120.0,
      unit_price: 1180.0,
      selection_reasons: [
        "Supplier MOQ (40.0 bags) is satisfied by pooled volume (43.5 bags)",
        "Supplier has 120.0 bags in stock (sufficient for 43.5 bags requirement)",
        "Geographical coverage within delivery radius"
      ],
      evaluated_suppliers: [
        {
          supplier_id: "sup_01",
          supplier_name: "Hyderabad Agro Wholesale Hub",
          moq: 40.0,
          available_stock: 120.0,
          service_radius_km: 15.0,
          unit_price: 1180.0,
          is_feasible: true,
          rejection_reasons: []
        },
        {
          supplier_id: "sup_02",
          supplier_name: "Sri Balaji Grain Merchants",
          moq: 60.0,
          available_stock: 200.0,
          service_radius_km: 10.0,
          unit_price: 1150.0,
          is_feasible: false,
          rejection_reasons: ["MOQ cannot be satisfied within the compatible retailer group (60.0 bags required > 43.5 bags)"]
        },
        {
          supplier_id: "sup_03",
          supplier_name: "Deccan Agro Supplies",
          moq: 30.0,
          available_stock: 25.0,
          service_radius_km: 12.0,
          unit_price: 1190.0,
          is_feasible: false,
          rejection_reasons: ["Available stock is below required pooled quantity (25.0 bags < 43.5 bags)"]
        }
      ]
    },
    created_at: "2026-08-13T12:00:00Z"
  },
  {
    id: "rec_002",
    product_id: "prod_006",
    product_name: "Freedom Sunflower Oil (15L Tin)",
    category: "Oils",
    pool_id: "pool_002",
    retailer_ids: ["ret_003", "ret_006", "ret_009"],
    retailer_names: [
      "Maruti Wholesale & Retail",
      "Bhavani Provision Store",
      "Durga Bhavani Kirana"
    ],
    threshold_status: "NEAR_THRESHOLD",
    threshold_quantity: 35.0,
    current_pool_quantity: 31.0,
    estimated_total_savings: 10230.0,
    estimated_savings_percentage: 16.9,
    average_cluster_distance_km: 2.4,
    unit_retail_price: 1950.0,
    unit_wholesale_price: 1620.0,
    explanation: "3 stores in Banjara Hills cluster are currently at 31.0 tins (88.5% of the 35.0 tin threshold). Adding 1 more store with 4 tins will unlock ₹10,230.00 total group savings (16.9% discount).",
    score: 0.91,
    pooled_inventory: {
      product_id: "prod_006",
      product_name: "Freedom Sunflower Oil (15L Tin)",
      unit: "tin",
      retailer_count: 3,
      total_quantity: 31.0,
      unit_weight_kg: 14.2,
      total_weight_kg: 440.2,
      supplier_moq: 35.0,
      moq_satisfied: false,
      moq_deficit: 4.0,
      retailer_demands: { ret_003: 11.0, ret_006: 12.0, ret_009: 8.0 }
    },
    transport: {
      total_load_kg: 440.2,
      total_quantity: 31.0,
      unit: "tin",
      recommended_vehicle: "Piaggio Ape E-City / E-Loader",
      vehicle_type: "3W_ELECTRIC",
      vehicle_capacity_kg: 500.0,
      capacity_utilization: 0.88,
      capacity_utilization_pct: 88.0,
      vehicles_required: 1,
      estimated_distance_km: 2.4,
      estimated_transit_time_mins: 38,
      delivery_stops_count: 3,
      estimated_total_cost_inr: 536.0,
      cost_per_retailer_inr: 178.67,
      individual_transport_cost_inr: 1200.0,
      transport_savings_inr: 664.0,
      transport_status: "SUITABLE",
      reason: "Piaggio Ape E-Loader (500 kg) selected: optimal 88.0% capacity utilization for 440.2 kg cargo. Note: Group is currently 4.0 tins below supplier wholesale MOQ.",
      vehicle_availability: "Available (In Fleet)",
      alternative_options: [
        { vehicle_id: "veh_3w_electric", vehicle_name: "Piaggio Ape E-Loader", capacity_kg: 500, capacity_utilization_pct: 88.0, is_feasible: true, estimated_cost_inr: 536 },
        { vehicle_id: "veh_scv_tata_ace", vehicle_name: "Tata Ace (SCV)", capacity_kg: 1000, capacity_utilization_pct: 44.0, is_feasible: true, estimated_cost_inr: 852 }
      ]
    },
    supplier_evaluation: {
      is_feasible: false,
      selected_supplier_id: "sup_04",
      selected_supplier_name: "Vijaya Oil Refineries",
      moq: 35.0,
      available_stock: 90.0,
      unit_price: 1620.0,
      selection_reasons: [
        "Supplier has sufficient stock (90.0 tins)",
        "Lowest wholesale pricing tier"
      ],
      evaluated_suppliers: [
        {
          supplier_id: "sup_04",
          supplier_name: "Vijaya Oil Refineries",
          moq: 35.0,
          available_stock: 90.0,
          service_radius_km: 20.0,
          unit_price: 1620.0,
          is_feasible: false,
          rejection_reasons: ["MOQ deficit: Pool volume 31.0 tins is below supplier MOQ of 35.0 tins (-4.0 tins needed)"]
        },
        {
          supplier_id: "sup_05",
          supplier_name: "Charminar Edible Traders",
          moq: 20.0,
          available_stock: 15.0,
          service_radius_km: 8.0,
          unit_price: 1680.0,
          is_feasible: false,
          rejection_reasons: ["Available stock is below required pooled quantity (15.0 tins < 31.0 tins)"]
        }
      ]
    },
    created_at: "2026-08-13T12:30:00Z"
  },
  {
    id: "rec_003",
    product_id: "prod_010",
    product_name: "Guntur Red Chilli Powder (5kg Pack)",
    category: "Spices",
    pool_id: "pool_003",
    retailer_ids: ["ret_004", "ret_007", "ret_011", "ret_014"],
    retailer_names: [
      "Ganesh General Store",
      "Santhoshi Mata Provisions",
      "Krishna Kirana",
      "Annapurna Traders"
    ],
    threshold_status: "ACHIEVED",
    threshold_quantity: 30.0,
    current_pool_quantity: 34.0,
    estimated_total_savings: 12240.0,
    estimated_savings_percentage: 20.5,
    average_cluster_distance_km: 3.1,
    unit_retail_price: 1750.0,
    unit_wholesale_price: 1390.0,
    explanation: "Cluster of 4 stores reached 34.0 packs, comfortably exceeding the 30.0 pack minimum wholesale threshold. Unlocks ₹12,240.00 in total group savings (20.5% discount).",
    score: 0.94,
    pooled_inventory: {
      product_id: "prod_010",
      product_name: "Guntur Red Chilli Powder (5kg Pack)",
      unit: "pack",
      retailer_count: 4,
      total_quantity: 34.0,
      unit_weight_kg: 5.0,
      total_weight_kg: 170.0,
      supplier_moq: 30.0,
      moq_satisfied: true,
      moq_deficit: 0.0,
      retailer_demands: { ret_004: 10.0, ret_007: 8.0, ret_011: 9.0, ret_014: 7.0 }
    },
    transport: {
      total_load_kg: 170.0,
      total_quantity: 34.0,
      unit: "pack",
      recommended_vehicle: "Piaggio Ape E-City / E-Loader",
      vehicle_type: "3W_ELECTRIC",
      vehicle_capacity_kg: 500.0,
      capacity_utilization: 0.34,
      capacity_utilization_pct: 34.0,
      vehicles_required: 1,
      estimated_distance_km: 3.1,
      estimated_transit_time_mins: 46,
      delivery_stops_count: 4,
      estimated_total_cost_inr: 621.5,
      cost_per_retailer_inr: 155.38,
      individual_transport_cost_inr: 1600.0,
      transport_savings_inr: 978.5,
      transport_status: "SUITABLE",
      reason: "Piaggio Ape E-Loader (500 kg) selected: sufficient capacity for 170.0 kg spice consignments with lowest cost per store (₹155.38).",
      vehicle_availability: "Available (In Fleet)",
      alternative_options: []
    },
    created_at: "2026-08-13T13:00:00Z"
  },
  {
    id: "rec_004",
    product_id: "prod_014",
    product_name: "Red Label Tea Master Pack (1kg x 12)",
    category: "Beverages",
    pool_id: "pool_004",
    retailer_ids: ["ret_010", "ret_012", "ret_015"],
    retailer_names: [
      "Shiva Super Market",
      "Nandi Superette",
      "Pavan Putra Kirana"
    ],
    threshold_status: "IN_PROGRESS",
    threshold_quantity: 20.0,
    current_pool_quantity: 14.0,
    estimated_total_savings: 11900.0,
    estimated_savings_percentage: 17.7,
    average_cluster_distance_km: 4.2,
    unit_retail_price: 4800.0,
    unit_wholesale_price: 3950.0,
    explanation: "3 Kirana stores in Madhapur area have pooled 14.0 master cartons (70% of 20.0 threshold). Requires 6 more cartons to unlock bulk tier discount.",
    score: 0.78,
    pooled_inventory: {
      product_id: "prod_014",
      product_name: "Red Label Tea Master Pack (1kg x 12)",
      unit: "carton",
      retailer_count: 3,
      total_quantity: 14.0,
      unit_weight_kg: 12.0,
      total_weight_kg: 168.0,
      supplier_moq: 20.0,
      moq_satisfied: false,
      moq_deficit: 6.0,
      retailer_demands: { ret_010: 5.0, ret_012: 5.0, ret_015: 4.0 }
    },
    transport: {
      total_load_kg: 168.0,
      total_quantity: 14.0,
      unit: "carton",
      recommended_vehicle: "Piaggio Ape E-City / E-Loader",
      vehicle_type: "3W_ELECTRIC",
      vehicle_capacity_kg: 500.0,
      capacity_utilization: 0.336,
      capacity_utilization_pct: 33.6,
      vehicles_required: 1,
      estimated_distance_km: 4.2,
      estimated_transit_time_mins: 48,
      delivery_stops_count: 3,
      estimated_total_cost_inr: 563.0,
      cost_per_retailer_inr: 187.67,
      individual_transport_cost_inr: 1300.0,
      transport_savings_inr: 737.0,
      transport_status: "UNDERUTILIZED",
      reason: "Piaggio Ape E-Loader capacity is sufficient (168.0 kg load). Pool is currently 6 cartons below supplier wholesale MOQ.",
      vehicle_availability: "Available (In Fleet)",
      alternative_options: []
    },
    created_at: "2026-08-13T13:15:00Z"
  },
  {
    id: "rec_005",
    product_id: "prod_018",
    product_name: "Surf Excel Easy Wash Carton (1kg x 20)",
    category: "Personal Care",
    pool_id: "pool_005",
    retailer_ids: ["ret_016", "ret_018", "ret_020", "ret_022"],
    retailer_names: [
      "Swagath Provisions",
      "Royal Superette",
      "Telangana General Store",
      "Deccan Superette"
    ],
    threshold_status: "ACHIEVED",
    threshold_quantity: 30.0,
    current_pool_quantity: 32.0,
    estimated_total_savings: 17600.0,
    estimated_savings_percentage: 19.6,
    average_cluster_distance_km: 2.9,
    unit_retail_price: 2800.0,
    unit_wholesale_price: 2250.0,
    explanation: "Group demand of 32.0 cartons easily passes the 30 carton supplier threshold, saving ₹17,600.00 across 4 retail partners.",
    score: 0.95,
    pooled_inventory: {
      product_id: "prod_018",
      product_name: "Surf Excel Easy Wash Carton (1kg x 20)",
      unit: "carton",
      retailer_count: 4,
      total_quantity: 32.0,
      unit_weight_kg: 20.0,
      total_weight_kg: 640.0,
      supplier_moq: 30.0,
      moq_satisfied: true,
      moq_deficit: 0.0,
      retailer_demands: { ret_016: 8.0, ret_018: 9.0, ret_020: 7.0, ret_022: 8.0 }
    },
    transport: {
      total_load_kg: 640.0,
      total_quantity: 32.0,
      unit: "carton",
      recommended_vehicle: "Tata Ace / Bolero Maxi Truck (SCV)",
      vehicle_type: "SCV",
      vehicle_capacity_kg: 1000.0,
      capacity_utilization: 0.64,
      capacity_utilization_pct: 64.0,
      vehicles_required: 1,
      estimated_distance_km: 2.9,
      estimated_transit_time_mins: 45,
      delivery_stops_count: 4,
      estimated_total_cost_inr: 938.8,
      cost_per_retailer_inr: 234.7,
      individual_transport_cost_inr: 2000.0,
      transport_savings_inr: 1061.2,
      transport_status: "SUITABLE",
      reason: "Tata Ace (SCV, 1,000 kg) selected: provides sufficient capacity for 640.0 kg load at 64.0% capacity utilization across 4 stores.",
      vehicle_availability: "Available (In Fleet)",
      alternative_options: []
    },
    created_at: "2026-08-13T13:45:00Z"
  }
];

export const MOCK_RETAILERS = [
  {
    id: "ret_001",
    name: "Sri Lakshmi Kirana & General Store",
    store_type: "Kirana",
    latitude: 17.3850,
    longitude: 78.4867,
    address: "Door No 42, Banjara Hills",
    city: "Hyderabad",
    pincode: "500034",
    contact_phone: "+91 9876543210",
    monthly_budget: 75000.0,
    rating: 4.8,
    forecasted_products_count: 6,
    total_savings_earned: 14250.0
  },
  {
    id: "ret_002",
    name: "Balaji Superette",
    store_type: "Superette",
    latitude: 17.3920,
    longitude: 78.4910,
    address: "Road No 12, Banjara Hills",
    city: "Hyderabad",
    pincode: "500034",
    contact_phone: "+91 9876543211",
    monthly_budget: 100000.0,
    rating: 4.9,
    forecasted_products_count: 8,
    total_savings_earned: 18900.0
  },
  {
    id: "ret_003",
    name: "Venkateshwara Traders",
    store_type: "Kirana",
    latitude: 17.3880,
    longitude: 78.4820,
    address: "Main Road, Jubilee Hills",
    city: "Hyderabad",
    pincode: "500033",
    contact_phone: "+91 9876543212",
    monthly_budget: 60000.0,
    rating: 4.7,
    forecasted_products_count: 5,
    total_savings_earned: 11400.0
  },
  {
    id: "ret_004",
    name: "Bhavani Provision Store",
    store_type: "General Store",
    latitude: 17.3750,
    longitude: 78.4750,
    address: "Panjagutta Colony",
    city: "Hyderabad",
    pincode: "500082",
    contact_phone: "+91 9876543213",
    monthly_budget: 45000.0,
    rating: 4.6,
    forecasted_products_count: 4,
    total_savings_earned: 8900.0
  },
  {
    id: "ret_005",
    name: "Sai Ram Kirana",
    store_type: "Kirana",
    latitude: 17.3810,
    longitude: 78.4890,
    address: "Somajiguda Market",
    city: "Hyderabad",
    pincode: "500082",
    contact_phone: "+91 9876543214",
    monthly_budget: 80000.0,
    rating: 4.8,
    forecasted_products_count: 7,
    total_savings_earned: 16100.0
  }
];

export const MOCK_PRODUCTS = [
  {
    id: "prod_001",
    name: "Sona Masoori Rice (25kg Bag)",
    category: "Grains",
    unit_of_measure: "bag",
    retail_price: 1450.0,
    wholesale_price: 1180.0,
    min_wholesale_quantity: 40.0,
    supplier_name: "Deccan Wholesale Grains",
    discount_pct: 18.6
  },
  {
    id: "prod_002",
    name: "Royal Toor Dal Premium (10kg)",
    category: "Grains",
    unit_of_measure: "bag",
    retail_price: 1600.0,
    wholesale_price: 1320.0,
    min_wholesale_quantity: 30.0,
    supplier_name: "Deccan Wholesale Grains",
    discount_pct: 17.5
  },
  {
    id: "prod_006",
    name: "Freedom Sunflower Oil (15L Tin)",
    category: "Oils",
    unit_of_measure: "tin",
    retail_price: 1950.0,
    wholesale_price: 1620.0,
    min_wholesale_quantity: 35.0,
    supplier_name: "Telangana Oil Mills",
    discount_pct: 16.9
  },
  {
    id: "prod_010",
    name: "Guntur Red Chilli Powder (5kg)",
    category: "Spices",
    unit_of_measure: "pack",
    retail_price: 1750.0,
    wholesale_price: 1390.0,
    min_wholesale_quantity: 30.0,
    supplier_name: "South India Spice Hub",
    discount_pct: 20.5
  }
];

export const MOCK_IMPACT = {
  impact: {
    total_community_savings_inr: 84520.0,
    average_group_discount_percentage: 18.5,
    wholesale_threshold_success_rate: 75.0,
    retailers_empowered: 30,
    logistics_trips_consolidated: 24,
    estimated_co2_reduction_kg: 100.8,
    average_roi_per_retailer_inr: 2817.33
  },
  comparison_table: [
    { product: "Sona Masoori Rice (25kg)", individual_price: 1450, pooled_price: 1180, savings_pct: 18.6, annual_savings: 32400 },
    { product: "Freedom Sunflower Oil (15L)", individual_price: 1950, pooled_price: 1620, savings_pct: 16.9, annual_savings: 39600 },
    { product: "Guntur Red Chilli Powder (5kg)", individual_price: 1750, pooled_price: 1390, savings_pct: 20.5, annual_savings: 43200 },
    { product: "Red Label Tea Master Pack", individual_price: 4800, pooled_price: 3950, savings_pct: 17.7, annual_savings: 51000 },
    { product: "Surf Excel Easy Wash Carton", individual_price: 2800, pooled_price: 2250, savings_pct: 19.6, annual_savings: 66000 }
  ]
};

export const MOCK_OPPORTUNITIES = [
  {
    opportunityId: "opp_demo_001",
    id: "opp_demo_001",
    productId: "prod_001",
    canonicalProductId: "grocery_rice_basmati",
    productName: "Basmati Rice (25kg Bag)",
    sectorId: "grocery",
    category: "Grains & Cereals",
    retailerIds: ["ret_001", "ret_002", "ret_005"],
    retailerCount: 3,
    retailerDemands: { "ret_001": 30.0, "ret_002": 25.0, "ret_005": 20.0 },
    retailerNames: ["Sri Lakshmi Kirana Store", "Balaji Superette", "Sai Ram Provisions"],
    supplierId: "sup_01",
    supplierName: "Deccan Wholesale Grains",
    combinedQuantity: 75.0,
    unit: "bags (25kg)",
    supplierAvailableQuantity: 500.0,
    supplierMOQ: 50.0,
    moqShortfall: 0.0,
    estimatedUnitPrice: 1180.0,
    estimatedTotalValue: 88500.0,
    geographicDistanceKm: 3.8,
    geographicFeasibility: "COMPATIBLE",
    feasibility: "FEASIBLE",
    status: "FEASIBLE",
    opportunityScore: 92.5,
    scoreLabel: "Feasible",
    reasons: [
      "3 retailers require the same canonical product (Basmati Rice)",
      "Combined demand (75.0 bags) satisfies supplier MOQ (50.0 bags)",
      "Supplier Deccan Wholesale Grains has 500.0 bags available",
      "Average cluster distance is 3.8 km"
    ],
    constraints: [
      "Supplier MOQ: 50.0 bags",
      "Supplier Stock: 500.0 bags",
      "Delivery Distance: 3.8 km"
    ],
    isAlreadyInPool: false,
    existingPoolId: null,
    isDemo: true,
    createdAt: "2026-09-23T12:00:00Z",
    updatedAt: "2026-09-23T12:00:00Z"
  },
  {
    opportunityId: "opp_demo_002",
    id: "opp_demo_002",
    productId: "prod_002",
    canonicalProductId: "grocery_pulses_toordal",
    productName: "Toor Dal Premium (50kg Bag)",
    sectorId: "grocery",
    category: "Pulses",
    retailerIds: ["ret_003", "ret_004"],
    retailerCount: 2,
    retailerDemands: { "ret_003": 15.0, "ret_004": 20.0 },
    retailerNames: ["Venkateshwara Traders", "Bhavani Provision Store"],
    supplierId: "sup_01",
    supplierName: "Deccan Wholesale Grains",
    combinedQuantity: 35.0,
    unit: "bags (50kg)",
    supplierAvailableQuantity: 400.0,
    supplierMOQ: 50.0,
    moqShortfall: 15.0,
    estimatedUnitPrice: 4850.0,
    estimatedTotalValue: 169750.0,
    geographicDistanceKm: 4.2,
    geographicFeasibility: "COMPATIBLE",
    feasibility: "BELOW_MOQ",
    status: "BELOW_MOQ",
    opportunityScore: 68.0,
    scoreLabel: "Needs 15.0 more demand",
    reasons: [
      "2 retailers require the same canonical product (Toor Dal)",
      "Combined demand is 35.0 bags",
      "Combined demand is below supplier MOQ (35.0 < 50.0 bags)",
      "Supplier Deccan Wholesale Grains has 400.0 bags available"
    ],
    constraints: [
      "Supplier MOQ: 50.0 bags",
      "Needs 15.0 bags additional compatible demand",
      "Available Supplier Stock: 400.0 bags"
    ],
    isAlreadyInPool: false,
    existingPoolId: null,
    isDemo: true,
    createdAt: "2026-09-23T12:00:00Z",
    updatedAt: "2026-09-23T12:00:00Z"
  },
  {
    opportunityId: "opp_demo_003",
    id: "opp_demo_003",
    productId: "prod_009",
    canonicalProductId: "grocery_oil_sunflower",
    productName: "Freedom Refined Sunflower Oil (15L Tin)",
    sectorId: "grocery",
    category: "Cooking Essentials",
    retailerIds: ["ret_001", "ret_006", "ret_007", "ret_008"],
    retailerCount: 4,
    retailerDemands: { "ret_001": 20.0, "ret_006": 20.0, "ret_007": 15.0, "ret_008": 15.0 },
    retailerNames: ["Sri Lakshmi Kirana Store", "Maruti Wholesale", "Ganesh General Store", "Venkateshwara Traders"],
    supplierId: "sup_02",
    supplierName: "Telangana Oil Mills",
    combinedQuantity: 70.0,
    unit: "tin",
    supplierAvailableQuantity: 45.0,
    supplierMOQ: 35.0,
    moqShortfall: 0.0,
    estimatedUnitPrice: 1620.0,
    estimatedTotalValue: 113400.0,
    geographicDistanceKm: 5.1,
    geographicFeasibility: "COMPATIBLE",
    feasibility: "INSUFFICIENT_STOCK",
    status: "INSUFFICIENT_STOCK",
    opportunityScore: 71.0,
    scoreLabel: "Limited by supplier stock",
    reasons: [
      "4 retailers require the same canonical product (Sunflower Oil)",
      "Combined demand (70.0 tin) satisfies supplier MOQ (35.0 tin)",
      "Supplier stock is below pooled requirement (45.0 < 70.0 tin)"
    ],
    constraints: [
      "Supplier MOQ: 35.0 tin",
      "Available Supplier Stock: 45.0 tin",
      "Inventory shortage of 25.0 tin"
    ],
    isAlreadyInPool: false,
    existingPoolId: null,
    isDemo: true,
    createdAt: "2026-09-23T12:00:00Z",
    updatedAt: "2026-09-23T12:00:00Z"
  }
];
