import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Brand & Navigation
    brandName: 'Samooh',
    brandBadge: 'AI',
    brandSubtitle: 'Group Procurement Core',
    mainPlatform: 'Main Platform',
    dashboard: 'Dashboard',
    opportunities: 'Opportunities',
    insights: 'Retailer Insights',
    impact: 'Business Impact',
    customDemand: 'Custom Demand Builder',
    savingsBill: 'Group Savings Bill',
    previousOrders: 'Previous Orders',
    previousOrdersNav: 'Previous Orders',
    ordersDesc: 'Complete order history, group savings bill archive, and delivery status tracking.',
    orderHistoryTitle: 'Kirana Wholesale Order History',
    viewInvoice: '📄 View Savings Bill',
    noPastOrders: 'No previous orders found for this account.',
    totalOrders: 'Total Orders Placed',
    lifetimeSavings: 'Lifetime Group Savings',
    statusDelivered: 'Delivered',
    statusInTransit: 'In Transit',
    statusProcessing: 'Processing',
    engineLive: 'Procurement Engine Live',
    retailersActive: '30 Retailers Active',
    searchPlaceholder: 'Search products, pools, retailers...',
    launchDemo: '🚀 Launch Hackathon Demo',
    loadingDemo: 'Loading Demo...',
    fastapiConnected: 'FastAPI Connected',
    demoMode: 'Demo Mode',
    retailAdmin: 'Sri Lakshmi Kirana',
    hyderabadHub: 'Hyderabad South-West Cluster',

    // Dashboard Page
    groupProcurementDashboard: 'Group Procurement Dashboard',
    demoStoreActive: 'Demo Store Active',
    dashboardDesc: 'Real-time aggregate retail demand, wholesale pool progress, and group savings.',
    resetSeedData: 'Reset / Seed Demo Data',
    seeding: 'Seeding...',
    estimatedSavings: 'Estimated Savings',
    netSavingsSub: 'Net community group savings',
    retailersBenefited: 'Retailers Benefited',
    retailersSub: 'Empowered retail store network',
    procurementPools: 'Procurement Pools',
    poolsSub: 'Active wholesale pools',
    avgSavingsPct: 'Average Savings %',
    avgSavingsSub: 'Off single-store retail price',
    monthlySavingsGrowth: 'Monthly Community Savings Growth',
    cumulativeSavingsDesc: 'Cumulative savings generated by group procurement',
    totalSaved: 'Total Saved',
    categoryBreakdown: 'Catalog Category Breakdown',
    categoryDesc: 'Product count across wholesale categories',
    highPriorityOpps: 'High-Priority Procurement Opportunities',
    liveAiClusters: 'Live AI matched procurement clusters',
    noPools: 'No active procurement pools generated yet.',
    seedAndGenerate: 'Seed Demo Data & Generate',
    backendUnreachable: 'Backend Server Unreachable',
    retryConnection: 'Retry Connection',
    seedBackendStart: 'Seed Backend & Start',

    // Opportunities Page
    procurementOpportunities: 'Procurement Opportunities',
    opportunitiesDesc: 'AI-clustered Kirana stores pooling demand to cross wholesale minimum order thresholds.',
    allOpps: 'All Opportunities',
    achieved: 'Threshold Achieved',
    nearThreshold: 'Near Threshold',
    inProgress: 'In Progress',
    targetProduct: 'Target Product',
    storesParticipating: 'Stores Participating',
    avgRadius: 'Average Radius',
    totalGroupSavings: 'Total Group Savings',
    viewDetails: 'View Details & Join Pool',
    accepted: 'Accepted & Locked',

    // Custom Demand Builder
    builderTitle: 'Custom Demand Builder',
    builderDesc: 'Select wholesale items, configure required quantities, and calculate live group savings before joining or creating a pool.',
    selectQuantity: 'Configure Order Quantities',
    singleStoreRetailTotal: 'Single Store Retail Cost',
    samoohGroupWholesaleTotal: 'Samooh Group Wholesale Cost',
    yourInstantSavings: 'Your Instant Group Savings',
    createGroupOrderBtn: '🚀 Create & Accept Custom Group Order',
    itemsInCart: 'Items Selected',
    unitMeasure: 'Unit',
    perUnit: 'per unit',
    bulkTierUnlocked: '🎉 Wholesale Bulk Tier Unlocked!',

    // Savings Bill / Invoice Page
    invoiceTitle: 'Official Group Purchase & Savings Bill',
    invoiceDesc: 'Itemized wholesale purchase order, GST breakdown, and guaranteed group savings certificate.',
    invoiceNo: 'Invoice No',
    billingDate: 'Billing Date',
    storeDetails: 'Billed Kirana Partner',
    clusterHubLabel: 'Logistics Cluster Hub',
    itemizedBreakdown: 'Itemized Wholesale Price Arbitrage',
    productDescription: 'Product Description',
    qtyOrdered: 'Qty Ordered',
    unitRetailPriceShort: 'Single Price',
    unitWholesalePriceShort: 'Samooh Price',
    totalRetailCost: 'Total Retail Cost',
    totalGroupCost: 'Total Samooh Cost',
    itemSavings: 'Net Savings',
    summaryHeading: 'Group Purchase Financial Summary',
    subtotalRetail: 'Subtotal (Standard Retail Price)',
    samoohGroupDiscount: 'Samooh Bulk Tier Discount (-)',
    subtotalWholesale: 'Wholesale Net Subtotal',
    taxGst: 'Taxes & GST (5% CGST/SGST)',
    logisticsDeliveryFee: 'Cluster Group Delivery Fee (Waived)',
    finalPayableAmount: 'Total Amount Payable',
    totalSavedHighlight: 'Total Money Saved by Joining Samooh',
    printInvoiceBtn: '🖨️ Print Savings Bill',
    downloadPdfBtn: '📥 Download PDF Receipt',
    guaranteeBadgeTitle: 'Official Samooh Group Savings Guarantee',
    guaranteeBadgeDesc: 'Verified by Samooh AI Engine. Guaranteed lowest wholesale tier price unlocked across 4 neighboring kirana stores in your cluster.',
    dispatchStatus: 'Group Dispatch Status',
    statusStep1: 'Order Pooled',
    statusStep2: 'Wholesale Minimum Achieved',
    statusStep3: 'Supplier Dispatch Assigned',
    statusStep4: 'Hub Delivery In-Transit',

    // Modal
    poolDetailTitle: 'Procurement Pool Details',
    unitRetailPrice: 'Unit Retail Price',
    unitWholesalePrice: 'Unit Wholesale Price',
    clusterRadius: 'Cluster Radius',
    thresholdProgress: 'Threshold Progress',
    participatingStores: 'Participating Retail Stores',
    retailerName: 'Retailer Name',
    predictedDemand: 'Predicted Demand',
    individualCost: 'Individual Cost',
    pooledCost: 'Samooh Cost',
    netSaved: 'Net Saved (₹)',
    savingsPct: 'Savings %',
    acceptPoolBtn: 'Accept Pool & View Savings Bill',

    // Retailer Insights Page
    insightsTitle: 'Retailer Insights & Forecasts',
    insightsDesc: '30-day AI predicted product demand across registered Kirana stores.',
    participatingStoresTitle: 'Registered Kirana Stores',
    monthlyBudget: 'Monthly Procurement Budget',
    rating: 'Rating',
    forecastTable: 'Granular 30-Day Demand Forecasts',
    product: 'Product',
    modelUsed: 'AI Model Used',
    confidenceScore: 'Confidence Score',
    runNewForecasts: 'Run New AI Forecasts',

    // Business Impact Page
    impactTitle: 'Business & ESG Impact Analysis',
    impactDesc: 'Quantifying financial ROI, supplier wholesale threshold success rate, and carbon offset.',
    co2Offset: 'CO2 Emission Offset',
    logisticsConsolidated: 'Logistics Consolidated',
    thresholdSuccessRate: 'Threshold Success Rate',
    totalCommunitySavings: 'Total Community Savings',
    refreshImpact: 'Refresh Impact Metrics',
    cumulativeSavingsGrowth: 'Cumulative Financial Savings Growth',
    grossSavedOverTime: 'Gross money saved by participating small retailers over time',
    avgGroupDiscount: 'Average Group Discount % Unlocked',
    discountOffRetail: 'Percentage discount off standard single-store retail price',
    pricingArbitrageTable: 'Wholesale Price Arbitrage Analysis',
    singleVsPooled: 'Single-store retail price vs Samooh pooled wholesale group price',
    annualSavings: 'Est. Annual Savings',
    avgNetSavings: 'Avg 18.5% Net Savings'
  },
  hi: {
    // Brand & Navigation
    brandName: 'समूह',
    brandBadge: 'AI',
    brandSubtitle: 'सामूहिक खरीद कोर',
    mainPlatform: 'मुख्य मंच',
    dashboard: 'डैशबोर्ड',
    opportunities: 'खरीद के अवसर',
    insights: 'रिटेलर इनसाइट्स',
    impact: 'व्यावसायिक प्रभाव',
    customDemand: 'कस्टम मांग बिल्डर',
    savingsBill: 'समूह बचत बिल',
    previousOrders: 'पिछले ऑर्डर्स',
    previousOrdersNav: 'पिछले ऑर्डर्स',
    ordersDesc: 'पूर्ण ऑर्डर इतिहास, समूह बचत बिल संग्रह और डिलीवरी स्थिति ट्रैकिंग।',
    orderHistoryTitle: 'किराना थोक ऑर्डर इतिहास',
    viewInvoice: '📄 बचत बिल देखें',
    noPastOrders: 'इस खाते के लिए कोई पिछला ऑर्डर नहीं मिला।',
    totalOrders: 'कुल दिए गए ऑर्डर',
    lifetimeSavings: 'जीवनकाल की कुल बचत',
    statusDelivered: 'डिलीवर हुआ',
    statusInTransit: 'डिलीवरी जारी',
    statusProcessing: 'प्रक्रिया में',
    engineLive: 'खरीद इंजन सक्रिय',
    retailersActive: '30 रिटेलर्स सक्रिय',
    searchPlaceholder: 'उत्पाद, थोक पूल, रिटेलर्स खोजें...',
    launchDemo: '🚀 हैकथॉन डेमो शुरू करें',
    loadingDemo: 'डेमो लोड हो रहा है...',
    fastapiConnected: 'फ़ास्ट-एपीआई कनेक्टेड',
    demoMode: 'डेमो मोड',
    retailAdmin: 'श्री लक्ष्मी किराना',
    hyderabadHub: 'हैदराबाद साउथ-वेस्ट क्लस्टर',

    // Dashboard Page
    groupProcurementDashboard: 'सामूहिक खरीद डैशबोर्ड',
    demoStoreActive: 'डेमो स्टोर सक्रिय',
    dashboardDesc: 'वास्तविक समय सामूहिक खुदरा मांग, थोक पूल प्रगति और समूह बचत की विस्तृत रिपोर्ट।',
    resetSeedData: 'डेमो डेटा रीसेट / री-सीड करें',
    seeding: 'सीडिंग जारी है...',
    estimatedSavings: 'अनुमानित कुल बचत',
    netSavingsSub: 'सामूहिक शुद्ध कुल बचत',
    retailersBenefited: 'लाभान्वित किराना स्टोर',
    retailersSub: 'सशक्त किराना स्टोर नेटवर्क',
    procurementPools: 'सक्रिय थोक पूल',
    poolsSub: 'सक्रिय थोक खरीद समूह',
    avgSavingsPct: 'औसत बचत प्रतिशत',
    avgSavingsSub: 'खुदरा मूल्य पर प्राप्त छूट',
    monthlySavingsGrowth: 'मासिक समुदाय बचत वृद्धि',
    cumulativeSavingsDesc: 'सामूहिक खरीद द्वारा अर्जित संचयी बचत',
    totalSaved: 'कुल अर्जित बचत',
    categoryBreakdown: 'उत्पाद श्रेणी विभाजन',
    categoryDesc: 'थोक श्रेणियों में उत्पादों की संख्या',
    highPriorityOpps: 'उच्च प्राथमिकता वाली खरीद के अवसर',
    liveAiClusters: 'एआई द्वारा मैच किए गए खरीद क्लस्टर',
    noPools: 'अभी कोई सक्रिय खरीद पूल उपलब्ध नहीं है।',
    seedAndGenerate: 'डेमो डेटा डालें और जनरेट करें',
    backendUnreachable: 'बैकएंड सर्वर अनुपलब्ध',
    retryConnection: 'पुनः प्रयास करें',
    seedBackendStart: 'बैकएंड प्रारंभ करें',

    // Opportunities Page
    procurementOpportunities: 'सामूहिक खरीद के अवसर',
    opportunitiesDesc: 'एआई-क्लस्टर्ड किराना स्टोर जो थोक न्यूनतम ऑर्डर सीमा पार करने के लिए मांग एकत्र कर रहे हैं।',
    allOpps: 'सभी अवसर',
    achieved: 'लक्ष्य प्राप्त हुआ',
    nearThreshold: 'लक्ष्य के करीब',
    inProgress: 'प्रगति पर है',
    targetProduct: 'लक्ष्य उत्पाद',
    storesParticipating: 'भाग लेने वाले स्टोर',
    avgRadius: 'औसत त्रिज्या',
    totalGroupSavings: 'कुल समूह बचत',
    viewDetails: 'विवरण देखें और पूल में शामिल हों',
    accepted: 'स्वीकृत और सुरक्षित',

    // Custom Demand Builder
    builderTitle: 'कस्टम मांग बिल्डर',
    builderDesc: 'अपनी आवश्यकता के उत्पाद और मात्रा चुनें, तथा समूह पूल में शामिल होने से पहले लाइव बचत देखें।',
    selectQuantity: 'ऑर्डर मात्रा निर्धारित करें',
    singleStoreRetailTotal: 'एकल खुदरा दुकान कुल लागत',
    samoohGroupWholesaleTotal: 'समूह थोक कुल लागत',
    yourInstantSavings: 'आपकी तत्काल समूह बचत',
    createGroupOrderBtn: '🚀 कस्टम समूह ऑर्डर बनाएं और स्वीकार करें',
    itemsInCart: 'चुने गए उत्पाद',
    unitMeasure: 'इकाई',
    perUnit: 'प्रति इकाई',
    bulkTierUnlocked: '🎉 थोक समूह छूट अनलॉक हो गई!',

    // Savings Bill / Invoice Page
    invoiceTitle: 'आधिकारिक समूह खरीद एवं बचत बिल',
    invoiceDesc: 'मद-वार थोक खरीद ऑर्डर, जीएसटी विवरण और गारंटीकृत समूह बचत प्रमाणपत्र।',
    invoiceNo: 'बिल नंबर',
    billingDate: 'बिलिंग तिथि',
    storeDetails: 'बिल प्राप्तकर्ता किराना स्टोर',
    clusterHubLabel: 'लॉजिस्टिक्स क्लस्टर हब',
    itemizedBreakdown: 'मद-वार थोक मूल्य अंतर विवरण',
    productDescription: 'उत्पाद विवरण',
    qtyOrdered: 'मात्रा',
    unitRetailPriceShort: 'खुदरा दर',
    unitWholesalePriceShort: 'समूह दर',
    totalRetailCost: 'कुल खुदरा लागत',
    totalGroupCost: 'कुल समूह थोक लागत',
    itemSavings: 'शुद्ध बचत',
    summaryHeading: 'समूह खरीद वित्तीय सारांश',
    subtotalRetail: 'उप-योग (मानक खुदरा मूल्य)',
    samoohGroupDiscount: 'समूह थोक छूट (-)',
    subtotalWholesale: 'शुद्ध थोक उप-योग',
    taxGst: 'कर एवं जीएसटी (5% CGST/SGST)',
    logisticsDeliveryFee: 'क्लस्टर डिलीवरी शुल्क (माफ)',
    finalPayableAmount: 'कुल देय राशि',
    totalSavedHighlight: 'समूह में शामिल होकर बचाई गई कुल राशि',
    printInvoiceBtn: '🖨️ बचत बिल प्रिंट करें',
    downloadPdfBtn: '📥 पीडीएफ रसीद डाउनलोड करें',
    guaranteeBadgeTitle: 'आधिकारिक समूह बचत गारंटी',
    guaranteeBadgeDesc: 'समूह एआई इंजन द्वारा सत्यापित। आपके क्लस्टर के किराना स्टोरों के साथ मिलकर सबसे कम थोक दर अनलॉक की गई।',
    dispatchStatus: 'समूह डिलीवरी स्थिति',
    statusStep1: 'ऑर्डर समेकित',
    statusStep2: 'थोक न्यूनतम सीमा पूर्ण',
    statusStep3: 'सप्लायर डिस्पैच असाइन',
    statusStep4: 'हब डिलीवरी इन-ट्रांजिट',

    // Modal
    poolDetailTitle: 'खरीद पूल विस्तृत विवरण',
    unitRetailPrice: 'इकाई खुदरा मूल्य',
    unitWholesalePrice: 'इकाई थोक मूल्य',
    clusterRadius: 'क्लस्टर दायरा',
    thresholdProgress: 'थोक लक्ष्य प्रगति',
    participatingStores: 'भाग लेने वाले किराना स्टोर',
    retailerName: 'रिटेलर का नाम',
    predictedDemand: 'अनुमानित मांग',
    individualCost: 'व्यक्तिगत लागत',
    pooledCost: 'समूह थोक लागत',
    netSaved: 'शुद्ध बचत (₹)',
    savingsPct: 'बचत %',
    acceptPoolBtn: 'पूल स्वीकार करें और बचत बिल देखें',

    // Retailer Insights Page
    insightsTitle: 'रिटेलर इनसाइट्स एवं पूर्वानुमान',
    insightsDesc: 'पंजीकृत किराना स्टोरों की 30-दिवसीय एआई अनुमानित उत्पाद मांग।',
    participatingStoresTitle: 'पंजीकृत किराना स्टोर नेटवर्क',
    monthlyBudget: 'मासिक खरीद बजट',
    rating: 'रेटिंग',
    forecastTable: '30-दिवसीय विस्तृत मांग पूर्वानुमान',
    product: 'उत्पाद',
    modelUsed: 'एआई मॉडल प्रयोग',
    confidenceScore: 'विश्वसनीयता स्कोर',
    runNewForecasts: 'नए एआई पूर्वानुमान चलाएं',

    // Business Impact Page
    impactTitle: 'व्यावसायिक एवं ईएसजी प्रभाव विश्लेषण',
    impactDesc: 'वित्तीय लाभ, थोक लक्ष्य सफलता दर और कार्बन उत्सर्जन में कमी का मूल्यांकन।',
    co2Offset: 'कार्बन उत्सर्जन में कमी (CO2)',
    logisticsConsolidated: 'समेकित लॉजिस्टिक्स ट्रिप',
    thresholdSuccessRate: 'थोक लक्ष्य सफलता दर',
    totalCommunitySavings: 'कुल समुदाय बचत',
    refreshImpact: 'प्रभाव आंकड़े अपडेट करें',
    cumulativeSavingsGrowth: 'संपादित वित्तीय बचत वृद्धि',
    grossSavedOverTime: 'समय के साथ छोटे किराना व्यापारियों द्वारा बचाई गई कुल राशि',
    avgGroupDiscount: 'औसत समूह छूट प्रतिशत',
    discountOffRetail: 'मानक खुदरा मूल्य पर प्राप्त कुल छूट',
    pricingArbitrageTable: 'थोक मूल्य अंतर विश्लेषण',
    singleVsPooled: 'व्यक्तिगत खुदरा मूल्य बनाम समूह थोक मूल्य तुलना',
    annualSavings: 'वार्षिक अनुमानित बचत',
    avgNetSavings: 'औसत 18.5% शुद्ध बचत'
  }
};

export const DEMO_USERS = {
  google_partner: {
    id: 'usr_google_01',
    storeName: 'Google Partner Kirana Store',
    ownerName: 'Google Merchant',
    email: 'google.user@gmail.com',
    password: 'google123',
    clusterHub: 'Hyderabad Tech Corridor Cluster #1',
    address: 'Door 101, IT Park Corridor, Gachibowli, Hyderabad (500032)',
    monthlyBudget: '₹3,20,000',
    totalSaved: '₹54,300',
    rating: 4.95,
    avatar: 'https://lh3.googleusercontent.com/a/default-user',
    isGoogle: true
  },
  sri_lakshmi: {
    id: 'usr_001',
    storeName: 'Sri Lakshmi Kirana & General Store',
    ownerName: 'Srinivas Rao',
    email: 'lakshmi@samooh.in',
    password: 'samooh123',
    clusterHub: 'Hyderabad South-West Wholesale Cluster #4',
    address: 'Door No 42, Road No 12, Banjara Hills, Hyderabad (500034)',
    monthlyBudget: '₹2,50,000',
    totalSaved: '₹42,850',
    rating: 4.9,
    avatar: null,
    isGoogle: false
  },
  balaji: {
    id: 'usr_002',
    storeName: 'Balaji Super Market',
    ownerName: 'Venkat Reddy',
    email: 'balaji@samooh.in',
    password: 'balaji123',
    clusterHub: 'Hyderabad Central Hub #2',
    address: 'Plot 18, Commercial Belt, Kukatpally, Hyderabad (500072)',
    monthlyBudget: '₹4,10,000',
    totalSaved: '₹68,400',
    rating: 4.8,
    avatar: null,
    isGoogle: false
  },
  venkatesh: {
    id: 'usr_003',
    storeName: 'Venkateshwara Traders',
    ownerName: 'K. Venkatesh',
    email: 'venkatesh@samooh.in',
    password: 'venky123',
    clusterHub: 'Hyderabad East Wholesale Cluster #7',
    address: 'Shop 5, Main Market Road, Uppal, Hyderabad (500039)',
    monthlyBudget: '₹1,85,000',
    totalSaved: '₹29,120',
    rating: 4.7,
    avatar: null,
    isGoogle: false
  }
};

export const DEFAULT_ORDERS = [
  {
    id: 'ord_901',
    invoiceNo: 'INV-2026-7712',
    date: '10 Aug 2026',
    userId: 'usr_001',
    storeName: 'Sri Lakshmi Kirana & General Store',
    clusterHub: 'Hyderabad South-West Wholesale Cluster #4',
    status: 'Delivered',
    statusColor: 'emerald',
    itemsCount: 18,
    totalRetailCost: 28400,
    totalWholesaleCost: 23100,
    totalSavings: 5300,
    overallSavingsPct: '18.6',
    finalPayable: 24255,
    items: [
      { id: 'prod_001', name: 'Sona Masoori Rice (25kg Bag)', qty: 8, retailPrice: 1450, wholesalePrice: 1180, lineRetail: 11600, lineWholesale: 9440, lineSavings: 2160, category: 'Grains & Pulses' },
      { id: 'prod_006', name: 'Freedom Sunflower Oil (15L Tin)', qty: 4, retailPrice: 1950, wholesalePrice: 1620, lineRetail: 7800, lineWholesale: 6480, lineSavings: 1320, category: 'Oils & Dairy' },
      { id: 'prod_010', name: 'Guntur Red Chilli Powder (5kg Pack)', qty: 6, retailPrice: 1500, wholesalePrice: 1180, lineRetail: 9000, lineWholesale: 7080, lineSavings: 1920, category: 'Spices & Condiments' }
    ]
  },
  {
    id: 'ord_902',
    invoiceNo: 'INV-2026-8842',
    date: '13 Aug 2026',
    userId: 'usr_google_01',
    storeName: 'Google Partner Kirana Store',
    clusterHub: 'Hyderabad Tech Corridor Cluster #1',
    status: 'In Transit',
    statusColor: 'blue',
    itemsCount: 22,
    totalRetailCost: 39650,
    totalWholesaleCost: 32210,
    totalSavings: 7440,
    overallSavingsPct: '18.8',
    finalPayable: 33821,
    items: [
      { id: 'prod_001', name: 'Sona Masoori Rice (25kg Bag)', qty: 10, retailPrice: 1450, wholesalePrice: 1180, lineRetail: 14500, lineWholesale: 11800, lineSavings: 2700, category: 'Grains & Pulses' },
      { id: 'prod_006', name: 'Freedom Sunflower Oil (15L Tin)', qty: 5, retailPrice: 1950, wholesalePrice: 1620, lineRetail: 9750, lineWholesale: 8100, lineSavings: 1650, category: 'Oils & Dairy' },
      { id: 'prod_010', name: 'Guntur Red Chilli Powder (5kg Pack)', qty: 4, retailPrice: 1750, wholesalePrice: 1390, lineRetail: 7000, lineWholesale: 5560, lineSavings: 1440, category: 'Spices & Condiments' },
      { id: 'prod_018', name: 'Surf Excel Easy Wash Carton (1kg x 20)', qty: 3, retailPrice: 2800, wholesalePrice: 2250, lineRetail: 8400, lineWholesale: 6750, lineSavings: 1650, category: 'Personal Care' }
    ]
  },
  {
    id: 'ord_903',
    invoiceNo: 'INV-2026-6410',
    date: '04 Aug 2026',
    userId: 'usr_002',
    storeName: 'Balaji Super Market',
    clusterHub: 'Hyderabad Central Hub #2',
    status: 'Delivered',
    statusColor: 'emerald',
    itemsCount: 35,
    totalRetailCost: 64200,
    totalWholesaleCost: 51800,
    totalSavings: 12400,
    overallSavingsPct: '19.3',
    finalPayable: 54390,
    items: [
      { id: 'prod_014', name: 'Red Label Tea Master Carton (1kg x 12)', qty: 5, retailPrice: 4800, wholesalePrice: 3950, lineRetail: 24000, lineWholesale: 19750, lineSavings: 4250, category: 'Beverages & Snacks' },
      { id: 'prod_001', name: 'Sona Masoori Rice (25kg Bag)', qty: 20, retailPrice: 1450, wholesalePrice: 1180, lineRetail: 29000, lineWholesale: 23600, lineSavings: 5400, category: 'Grains & Pulses' },
      { id: 'prod_006', name: 'Freedom Sunflower Oil (15L Tin)', qty: 10, retailPrice: 1120, wholesalePrice: 845, lineRetail: 11200, lineWholesale: 8450, lineSavings: 2750, category: 'Oils & Dairy' }
    ]
  }
];

const AppContext = createContext();

export function AppProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('samooh_theme') || 'light');
  const [lang, setLang] = useState(() => localStorage.getItem('samooh_lang') || 'en');
  const [activeInvoice, setActiveInvoice] = useState(null);
  
  const [user, setUser] = useState(() => {
    const saved = localStorage.getItem('samooh_user');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        return DEMO_USERS.sri_lakshmi;
      }
    }
    return DEMO_USERS.sri_lakshmi;
  });

  const [orderHistory, setOrderHistory] = useState(() => {
    const saved = localStorage.getItem('samooh_orders');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        return DEFAULT_ORDERS;
      }
    }
    return DEFAULT_ORDERS;
  });

  useEffect(() => {
    localStorage.setItem('samooh_orders', JSON.stringify(orderHistory));
  }, [orderHistory]);

  useEffect(() => {
    localStorage.setItem('samooh_theme', theme);
    if (theme === 'light') {
      document.documentElement.classList.remove('dark');
      document.documentElement.classList.add('light');
    } else {
      document.documentElement.classList.remove('light');
      document.documentElement.classList.add('dark');
    }
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('samooh_lang', lang);
  }, [lang]);

  useEffect(() => {
    if (user) {
      localStorage.setItem('samooh_user', JSON.stringify(user));
    } else {
      localStorage.removeItem('samooh_user');
    }
  }, [user]);

  const addOrderToHistory = (newInvoice) => {
    const orderObj = {
      id: `ord_${Date.now()}`,
      invoiceNo: newInvoice.invoiceNo || `INV-2026-${Math.floor(1000 + Math.random() * 9000)}`,
      date: newInvoice.date || new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
      userId: user?.id || 'usr_001',
      storeName: newInvoice.storeName || user?.storeName || 'Sri Lakshmi Kirana',
      clusterHub: newInvoice.clusterHub || user?.clusterHub || 'Hyderabad Cluster',
      status: 'In Transit',
      statusColor: 'blue',
      itemsCount: newInvoice.totalItemsCount || (newInvoice.items ? newInvoice.items.length : 1),
      totalRetailCost: newInvoice.totalRetailCost || 0,
      totalWholesaleCost: newInvoice.totalWholesaleCost || 0,
      totalSavings: newInvoice.totalSavings || 0,
      overallSavingsPct: newInvoice.overallSavingsPct || '18.5',
      finalPayable: newInvoice.finalPayable || 0,
      items: newInvoice.items || []
    };

    setOrderHistory(prev => [orderObj, ...prev]);
  };

  const toggleTheme = () => {
    setTheme((prev) => (prev === 'light' ? 'dark' : 'light'));
  };

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  const loginWithGoogle = () => {
    const googleUser = DEMO_USERS.google_partner;
    setUser(googleUser);
    return googleUser;
  };

  const login = (email, password) => {
    const found = Object.values(DEMO_USERS).find(
      u => u.email.toLowerCase() === email.toLowerCase() && u.password === password
    );
    if (found) {
      setUser(found);
      return { success: true, user: found };
    }
    // Fallback: create dynamic session for any email
    const dynamicUser = {
      id: `usr_${Date.now()}`,
      storeName: email.split('@')[0].toUpperCase() + ' Kirana Store',
      ownerName: email.split('@')[0],
      email: email,
      password: password,
      clusterHub: 'Hyderabad South-West Cluster #4',
      address: 'Plot 12, Main Road, Hyderabad',
      monthlyBudget: '₹2,00,000',
      totalSaved: '₹15,000',
      rating: 4.8,
      avatar: null,
      isGoogle: false
    };
    setUser(dynamicUser);
    return { success: true, user: dynamicUser };
  };

  const logout = () => {
    setUser(DEMO_USERS.sri_lakshmi);
  };

  const switchUser = (userKey) => {
    if (DEMO_USERS[userKey]) {
      setUser(DEMO_USERS[userKey]);
    }
  };

  return (
    <AppContext.Provider value={{ 
      theme, 
      setTheme, 
      toggleTheme, 
      lang, 
      setLang, 
      toggleLanguage, 
      t,
      activeInvoice,
      setActiveInvoice,
      user,
      setUser,
      orderHistory,
      addOrderToHistory,
      loginWithGoogle,
      login,
      logout,
      switchUser
    }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}
